import {lazy,Suspense,useCallback,useState} from 'react';
import {Crosshair,ChevronRight,ArrowLeft,Lock,Star,PawPrint,Settings as SettingsIcon,Shield,Radio,MapPin,Clock,Check,RotateCcw,Target,Volume2,BookOpen} from 'lucide-react';
import {missions,missionBriefing} from '../data/missions';
import {load,save,type Settings} from '../services/save';
import type {MissionResult} from '../game/rules';
const GameCanvas=lazy(()=>import('../game/GameCanvas'));
type Screen='home'|'missions'|'briefing'|'game'|'result'|'loadout'|'dossier'|'settings';
const asset=(name:string)=>`${import.meta.env.BASE_URL}images/${name}`;
export default function App(){
 const [screen,setScreen]=useState<Screen>('home');const [progress,setProgress]=useState(load);const [result,setResult]=useState<MissionResult|null>(null);const [saveError,setSaveError]=useState(false);const [attempt,setAttempt]=useState(0);
 const [selected,setSelected]=useState(1);const mission=missions[selected-1];const unlocked=(id:number)=>id===1||!!progress.completed[id-1];
 const t=(it:string,en:string)=>progress.settings.language==='it'?it:en;const language=progress.settings.language;
 const finish=useCallback((r:MissionResult)=>{setResult(r);if(r.success)setProgress(p=>{const previous=p.completed[selected];const first=!previous;const completed={...p.completed,[selected]:{stars:Math.max(previous?.stars??0,r.stars),time:Math.min(previous?.time??90,r.time),accuracy:Math.max(previous?.accuracy??0,r.accuracy)}};const next={...p,completed,stars:Object.values(completed).reduce((sum,v)=>sum+v.stars,0),bestTime:Math.min(p.bestTime??90,r.time),bestAccuracy:Math.max(p.bestAccuracy,r.accuracy),credits:p.credits+(first?r.reward:0)};setSaveError(!save(next));return next;});setScreen('result');},[selected]);
 function setting<K extends keyof Settings>(key:K,value:Settings[K]){setProgress(p=>{const next={...p,settings:{...p.settings,[key]:value}};setSaveError(!save(next));return next;});}
 function start(){setAttempt(n=>n+1);setScreen('game');}
 if(screen==='game')return <Suspense fallback={<div className="loading"><Crosshair className="spin"/><span>{t('Connessione al porto…','Connecting to harbor…')}</span></div>}><GameCanvas key={attempt} mission={mission} settings={progress.settings} onResult={finish} onExit={()=>setScreen('home')}/></Suspense>;
 const titles={home:'',missions:t('Operazioni','Operations'),briefing:t('Briefing missione','Mission briefing'),result:t('Rapporto operativo','Operation report'),loadout:t('Equipaggiamento','Loadout'),dossier:'Dossier',settings:t('Impostazioni','Settings')};
 return <div className={`app screen-${screen}`}>
 <header className="topbar"><button className="wordmark" onClick={()=>setScreen('home')} aria-label="CAPI Home"><Crosshair/><span>CAPI<span className="wordmark-sub">SHADOW MISSIONS</span></span></button><div className="top-status"><span className="status-dot"/>{t('CANALE SICURO','SECURE CHANNEL')}<span className="divider"/>CHAPTER 01</div><button className="icon-button" aria-label={t('Impostazioni','Settings')} onClick={()=>setScreen('settings')}><SettingsIcon size={20}/></button></header>
 {screen!=='home'&&<div className="page-heading"><button className="back" onClick={()=>setScreen(screen==='briefing'?'missions':'home')}><ArrowLeft size={17}/>{t('INDIETRO','BACK')}</button><span>{titles[screen]}</span><span className="eyebrow">CAPI / 01</span></div>}
 <main>
 {screen==='home'&&<>
 <section className="home-hero"><div className="hero-art" role="img" aria-label={t('Isa e Docky in missione a Milano','Isa and Docky on a mission in Milan')}/><div className="hero-grid"/><div className="hero-content"><div className="chapter-label"><span/>CHAPTER 01 <i/> {t('LE OMBRE DI MILANO','THE SHADOWS OF MILAN')}</div><h1>CAPI<span>SHADOW<br/>MISSIONS<span className="red-period">.</span></span></h1><p className="hero-quote">{t('Alcuni eroi lavorano in silenzio.','Some heroes work in silence.')}</p><p className="hero-description">{t('Un colpo. Una scelta. Una verità da scoprire.','One shot. One choice. One truth to uncover.')}<br/>{t('Con Docky al tuo fianco. Sempre.','With Docky by your side. Always.')}</p><button className="primary hero-cta" onClick={()=>setScreen('missions')}><Crosshair size={20}/>{progress.stars?t('CONTINUA','CONTINUE'):t('INIZIA OPERAZIONE','BEGIN OPERATION')}<ChevronRight size={20}/></button><div className="hero-meta"><span className="status-dot"/>{t('10 MISSIONI · SBLOCCO PROGRESSIVO','10 MISSIONS · PROGRESSIVE UNLOCK')}<span>WEB 3D · DEMO</span></div></div><div className="agent-tag"><span className="tiny-line"/><span>ISA <b>“CAPI”</b><small>{t('AGENTE OPERATIVO','FIELD AGENT')}</small></span><span className="agent-tag-docky"><PawPrint size={18}/> DOCKY<small>{t('COMPAGNO DI SQUADRA','TEAM COMPANION')}</small></span></div></section>
 <section className="base-strip"><div><span className="eyebrow">{t('IL TUO PERCORSO','YOUR PROGRESS')}</span><strong>CHAPTER 01</strong></div><div className="progress-track"><div><span>{t('Operazioni completate','Operations completed')}</span><b>{String(Object.keys(progress.completed).length).padStart(2,'0')} <em>/ 10</em></b></div><div className="track"><i style={{width:`${Object.keys(progress.completed).length*10}%`}}/></div></div><div className="stat"><Star/><strong>{progress.stars}<small>/ 30</small></strong><span>{t('STELLE','STARS')}</span></div><div className="stat"><Shield/><strong>{progress.credits.toLocaleString(language)}</strong><span>{t('CREDITI','CREDITS')}</span></div></section>
 <section className="home-navigation"><button className="nav-card mission-nav" onClick={()=>setScreen('missions')}><div className="card-icon"><Target/></div><div><span className="eyebrow">01 / {t('OPERAZIONI','OPERATIONS')}</span><h2>{t('Scegli la missione','Choose your mission')}</h2><p>{t('Ogni incarico nasconde una storia.','Every assignment hides a story.')}</p></div><ChevronRight/></button><button className="nav-card" onClick={()=>setScreen('loadout')}><div className="card-icon"><Crosshair/></div><div><span className="eyebrow">02 / LOADOUT</span><h2>{t('Pronta all’azione','Ready for action')}</h2><p>SR-01 Scout · {t('Equipaggiato','Equipped')}</p></div><ChevronRight/></button><button className="nav-card" onClick={()=>setScreen('dossier')}><div className="card-icon"><BookOpen/></div><div><span className="eyebrow">03 / INTELLIGENCE</span><h2>{t('Il dossier','The dossier')}</h2><p>{t('Isa, Docky e il filo invisibile.','Isa, Docky and the invisible thread.')}</p></div><ChevronRight/></button></section>
 <div className="radio-strip"><Radio size={18}/><span>{t('ULTIMA TRASMISSIONE','LATEST TRANSMISSION')}</span><p>{t('“CAPI, abbiamo intercettato un carico sospetto. Ti invio le coordinate.”','“CAPI, we intercepted a suspicious shipment. Sending coordinates.”')}</p><b>23:47</b></div>
 </>}
 {screen==='missions'&&<section className="page-content"><div className="section-intro"><span className="eyebrow">CHAPTER 01 / {t('IL FILO INVISIBILE','THE INVISIBLE THREAD')}</span><h1>{t('Ogni scelta lascia una traccia.','Every choice leaves a trace.')}</h1><p>{t('Supera ogni operazione per sbloccare la successiva: meno tempo, pattuglie più rapide e più obiettivi.','Complete each operation to unlock the next: less time, faster patrols and more targets.')}</p></div><div className="missions-grid">{missions.map(m=><button key={m.id} className={`mission-card ${unlocked(m.id)?'available':'locked'}`} disabled={!unlocked(m.id)} onClick={()=>{setSelected(m.id);setScreen('briefing')}}><div className={`mission-image environment-${m.environment}`}><div className="port-art"><i/><i/><i/></div><span className="mission-number">{String(m.id).padStart(2,'0')}</span>{!unlocked(m.id)&&<Lock size={22}/>}<span className="mission-status">{unlocked(m.id)?t('GIOCABILE','PLAYABLE'):t('BLOCCATA','LOCKED')}</span></div><div className="mission-copy"><span className="eyebrow">{m.location[language]}</span><h2>{m.name[language]}</h2><p>{m.description[language]}</p><div className="mission-bottom"><span>{'■'.repeat(m.difficulty)}<em>{'□'.repeat(5-m.difficulty)}</em></span>{unlocked(m.id)?<span className="stars">{'★'.repeat(progress.completed[m.id]?.stars??0)}{'☆'.repeat(3-(progress.completed[m.id]?.stars??0))}</span>:<Lock size={14}/>}</div></div></button>)}</div></section>}
 {screen==='briefing'&&<section className="briefing page-content"><div className="briefing-main"><span className="eyebrow red"><Radio size={16}/> INCOMING ENCRYPTED TRANSMISSION</span><h1>{t('Operazione','Operation')}<br/>{mission.name[language]}<span className="red-period">.</span></h1><div className="briefing-location"><MapPin size={16}/>{mission.location[language]}<span>23:47 CET</span></div><div className="briefing-art"><div className="port-art"><i/><i/><i/></div><span>CLASSIFIED / EYES ONLY</span><Crosshair size={90}/></div><div className="transmission"><div className="handler"><Radio/><span>CONTROL<small>ENCRYPTED CHANNEL 07</small></span><span className="status-dot"/></div><p>“{missionBriefing(mission,language)}”</p></div></div><aside className="briefing-aside"><span className="eyebrow">MISSION INTELLIGENCE</span><h2>{t('Osserva. Identifica. Agisci.','Observe. Identify. Act.')}</h2><div className="intel-target"><Target/><div><h3>{`${mission.targets} ${t('obiettivi','targets')}`}</h3><p>{t('Fascia rossa al braccio. Usa Docky Scan per confermare.','Red armband. Use Docky Scan to confirm.')}</p></div></div><div className="objective-list"><p><Check/>{t('Neutralizza tutti gli obiettivi','Neutralize all targets')}</p><p><Shield/>{t('Non colpire civili o altri uomini','Do not shoot civilians or other men')}</p><p><Clock/>{`${mission.timeLimit} s · ${t('poi ti scoprono','then you are discovered')}`}</p><p><Crosshair/>{t('Precisione ≥ 70% per 3 stelle','Accuracy ≥ 70% for 3 stars')}</p></div><div className="docky-note"><img src={asset('docky.jpg')} alt="Docky"/><div><strong><PawPrint size={15}/> DOCKY SCAN</strong><p>{t('Il suo istinto rivela gli obiettivi per 5 secondi. Recupero: 30 s.','His instincts reveal the targets for 5 seconds. Cooldown: 30 s.')}</p></div></div><div className="reward"><span>{t('RICOMPENSA PRIMO COMPLETAMENTO','FIRST COMPLETION REWARD')}</span><strong>{mission.reward.toLocaleString(language)} <small>CR</small></strong></div><button className="primary" onClick={start}>{t('INIZIA MISSIONE','START MISSION')}<ChevronRight size={20}/></button><p className="control-note">{t('Tocca o trascina per mirare · Joystick · Zoom +/−','Tap or drag to aim · Joystick · Zoom +/−')}</p></aside></section>}
 {screen==='result'&&result&&<section className="result-page"><span className="eyebrow">OPERATION {String(selected).padStart(2,'0')} / DEBRIEF</span><div className={`result-emblem ${result.success?'':'failed'}`}>{result.success?<Shield size={46}/>:<Target size={46}/>}</div><h1>{result.success?t('Missione completata','Mission complete'):t('Missione fallita','Mission failed')}</h1><p>{result.success?t('Obiettivi neutralizzati. Settore messo in sicurezza.','Targets neutralized. Sector secured.'):result.reason==='civilian'?t('Hai colpito un civile. Osserva gli indizi prima di sparare.','You hit a civilian. Observe the clues before shooting.'):result.reason==='wrong'?t('Bersaglio non autorizzato. Cerca la fascia rossa al braccio.','Unauthorized target. Look for the red armband.'):t('Tempo scaduto. Ti hanno scoperta e colpita.','Time ran out. They discovered you and opened fire.')}</p><div className="result-stars">{[1,2,3].map(n=><Star key={n} size={45} fill={n<=result.stars?'currentColor':'none'} className={n<=result.stars?'earned':''}/>)}</div><div className="result-stats"><div><span>{t('PRECISIONE','ACCURACY')}</span><strong>{result.accuracy}%</strong></div><div><span>{t('TEMPO','TIME')}</span><strong>{result.time.toFixed(1)}s</strong></div><div><span>{t('COLPI','SHOTS')}</span><strong>{result.shots}</strong></div><div><span>{t('BERSAGLI COLPITI','TARGETS HIT')}</span><strong>{result.hits}</strong></div></div>{result.success&&<div className="outro"><PawPrint/><p>{selected===10?t('Docky è al sicuro. Control conferma: rete smantellata.','Docky is safe. Control confirms: network dismantled.'):t('Docky ha trovato una nuova pista. Control invia le coordinate della prossima operazione.','Docky found a new lead. Control sends coordinates for the next operation.')}</p></div>}<div className="result-actions">{result.success&&selected<10&&<button className="primary" onClick={()=>{setSelected(selected+1);setScreen('briefing')}}>{t('PROSSIMA MISSIONE','NEXT MISSION')}<ChevronRight/></button>}{result.success&&selected===10&&<strong>{t('CAMPAGNA COMPLETATA · Docky è al sicuro.','CAMPAIGN COMPLETE · Docky is safe.')}</strong>}<button className="primary" onClick={start}><RotateCcw size={18}/>{t('RIPROVA MISSIONE','RETRY MISSION')}</button><button onClick={()=>setScreen('missions')}>{t('SELEZIONE MISSIONI','MISSION SELECT')}<ChevronRight size={18}/></button></div></section>}
 {screen==='loadout'&&<section className="page-content"><div className="section-intro"><span className="eyebrow">ARMORY / CAPI</span><h1>{t('La precisione è una scelta.','Precision is a choice.')}</h1><p>{t('SR-01 Scout è equipaggiato. Le altre armi saranno disponibili in un futuro aggiornamento.','SR-01 Scout is equipped. Other weapons will be available in a future update.')}</p></div><div className="weapons">{[{name:'SR-01 Scout',stats:[60,55,8,55]},{name:'SR-12 Tactical',stats:[75,70,6,65]},{name:'Viper X',stats:[90,85,8,75]}].map((w,i)=><article className={`weapon ${i?'locked':''}`} key={w.name}><span className="eyebrow">{i?t('CLASSIFICATO','CLASSIFIED'):t('EQUIPAGGIATO','EQUIPPED')}</span><div className="rifle"><span/><i/><b/><em/></div><h2>{w.name}</h2>{[t('Danno','Damage'),t('Stabilità','Stability'),'Zoom',t('Ricarica','Reload')].map((s,j)=><div className="weapon-stat" key={s}><span>{s}</span><div><i style={{width:`${j===2?w.stats[j]*10:w.stats[j]}%`}}/></div><b>{w.stats[j]}{j===2?'×':''}</b></div>)}<div className="weapon-state">{i?<Lock size={16}/>:<Check size={16}/>} {i?t('In arrivo','Coming soon'):'SR-01 / READY'}</div></article>)}</div></section>}
 {screen==='dossier'&&<section className="page-content dossier"><div className="dossier-photo"><img src={asset('isa-docky.jpeg')} alt={t('Isa e Docky davanti al Duomo','Isa and Docky at the Duomo')}/><span>PERSONNEL FILE / 001</span></div><div><span className="eyebrow red">CLASSIFIED / CHAPTER 01</span><h1>Isa.<br/>{t('Nome in codice: CAPI.','Codename: CAPI.')}</h1><p>{t('Calma, determinata, poche parole. Isa lavora nell’ombra per una rete di intelligence. La sua vita è fatta di dettagli che gli altri non vedono.','Calm, determined, a woman of few words. Isa works in the shadows for an intelligence network. Her life is made of details others overlook.')}</p><h2><PawPrint/> Docky</h2><p>{t('Un Labrador color miele, una pettorina rossa, una lealtà senza condizioni. Per Isa, Docky è famiglia. Nelle missioni il suo fiuto può fare la differenza.','A honey-colored Labrador, a red harness, unconditional loyalty. To Isa, Docky is family. His nose can make all the difference on a mission.')}</p><blockquote>{t('“Con Docky al mio fianco, nessuna missione è impossibile.”','“With Docky by my side, no mission is impossible.”')}</blockquote><span className="eyebrow">{t('IL FILO INVISIBILE','THE INVISIBLE THREAD')}</span><p>{t('Un carico al porto. Il numero 419. Una voce che interrompe la trasmissione. Gli incarichi sembrano scollegati. Non lo sono.','A shipment at the harbor. The number 419. A voice cutting off a transmission. The assignments seem unrelated. They are not.')}</p></div></section>}
 {screen==='settings'&&<section className="settings page-content"><span className="eyebrow">PERSONAL CONFIGURATION</span><h1>{t('Il tuo modo di giocare.','Your way to play.')}</h1><label>{t('Lingua','Language')}<select value={language} onChange={e=>setting('language',e.target.value as Settings['language'])}><option value="it">Italiano</option><option value="en">English</option></select></label>{(['music','sfx','sensitivity'] as const).map((s,i)=><label key={s}><span><Volume2 size={17}/>{[t('Atmosfera audio','Audio ambience'),t('Effetti sonori','Sound effects'),t('Sensibilità mira','Aim sensitivity')][i]}</span><input aria-label={s} type="range" min={s==='sensitivity'?.3:0} max={s==='sensitivity'?2:1} step="0.05" value={progress.settings[s]} onChange={e=>setting(s,Number(e.target.value))}/></label>)}<label>{t('Qualità grafica','Graphics quality')}<select value={progress.settings.quality} onChange={e=>setting('quality',e.target.value as Settings['quality'])}>{['AUTO','LOW','MEDIUM','HIGH'].map(q=><option key={q}>{q}</option>)}</select></label>{(['vibration','leftHanded','reducedShake','subtitles'] as const).map((s,i)=><label key={s}>{[t('Vibrazione','Vibration'),t('Modalità mancini','Left-handed controls'),t('Riduci oscillazione e rinculo','Reduce sway and recoil'),t('Sottotitoli e suggerimenti','Subtitles and hints')][i]}<input type="checkbox" checked={progress.settings[s]} onChange={e=>setting(s,e.target.checked)}/></label>)}<p className="control-note">{t('Salvataggio automatico su questo dispositivo. Desktop: Spazio = sparo, R = ricarica, B = respiro, Q = Docky, Esc = pausa, WASD/frecce = mira, +/− = zoom.','Automatically saved on this device. Desktop: Space = fire, R = reload, B = breath, Q = Docky, Esc = pause, WASD/arrows = aim, +/− = zoom.')}</p></section>}
 </main><footer><span>CAPI <b>/</b> SHADOW MISSIONS</span><span>{t('PRECISIONE. ISTINTO. LEALTÀ.','PRECISION. INSTINCT. LOYALTY.')}</span><span>CHAPTER 01 · DEMO v0.3</span></footer>{saveError&&<div className="save-warning" role="alert">{t('Salvataggio non disponibile: il progresso resta valido solo per questa sessione.','Storage unavailable: progress is kept for this session only.')}</div>}
 </div>;
}
